# Generated by Django 5.0 on 2023-12-16 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=150, null=True, verbose_name='место выполнения')),
                ('time_when', models.TimeField(auto_now_add=True, verbose_name='время, когда выполнять')),
                ('action', models.CharField(max_length=150, verbose_name='действие')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('periodical', models.PositiveIntegerField(default=1, verbose_name='периодичность (в днях)')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='вознаграждение')),
                ('time_duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='время выполнения (в сек.)')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='создатель')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
