# Generated by Django 5.0 on 2023-12-19 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tg_bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_chat_id',
            field=models.CharField(max_length=50, verbose_name='chatID пользователя'),
        ),
    ]
