# Generated by Django 5.0 on 2023-12-19 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_time_when'),
        ('tg_bot', '0002_alter_tguser_tg_chat_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='TgMassages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_date', models.DateField(verbose_name='дата отправки сообщения')),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habits.habit', verbose_name='привычка')),
                ('tg_chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tg_bot.tguser', verbose_name='chatID пользователя')),
            ],
            options={
                'verbose_name': 'Сообщение в ТГ',
                'verbose_name_plural': 'Сообщения в ТГ',
            },
        ),
    ]
