# Generated by Django 5.0 on 2023-12-20 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habits', '0002_alter_habit_time_when'),
        ('tg_bot', '0004_rename_tgmassages_tgmessages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TgMessages',
            new_name='TgMessage',
        ),
    ]
